### ISSUE TITLE
vis shell out to ripgrep

### ISSUE THREAD

**Issue by jgarte** [evanrelf/dotfiles#2]
Hi @evanrelf 

I'm just sharing this vis config that I've taken inspiration from as an example of how to shell out to ripgrep:

https://github.com/ninewise/dotfiles/blob/b4fc540c87c9933e4e4a3ed8cf2b10c9e1e2396b/config/vis/visrc.lua#L76

relevant snippet:

```
vis:command_register("rg", function(argv, force, cur_win, selection, range)
	local out = io.popen("sk --ansi -i -c 'rg --color=always --line-number "..'"{}"'.."'"):read()
	if out then
		local filename = string.find(out, ':')
		local linenumber = string.find(out, ':', filename + 1)
		vis:command(string.format(argv[1]..' "%s"', string.sub(out, 0, filename - 1)))
		vis.win.selection:to(tonumber(string.sub(out, filename + 1, linenumber - 1)), 0)
		vis:feedkeys("<vis-redraw>")
	end
end, 'fuzzy grep open')

vis:map(vis.modes.NORMAL, ";g", function()
	vis:command('rg vsplit')
end)

vis:map(vis.modes.NORMAL, ";G", function()
	vis:command('rg e')
end)
```

ps. The directory below has great examples of vis usage through tests:

https://github.com/martanne/vis-test

# A lexer for literate haskell

https://github.com/ninewise/dotfiles/blob/21f8233eda96afd0dc7d2ce6ae9e06965ceb05a4/config/vis/lexers/lithaskell.lua

# A simple alternative lexer for scheme

https://milesalan.com/notes/simple-lpeg-for-lisp/

**Comment by evanrelf** [comment]
Hi @jgarte 🙂 Thanks for sharing.

I tried Vis after we talked about it last time.

As much as I like how it uses Lua, and does parsing instead of regex for syntax highlighting, in other ways it feels less mature than Kakoune. Kakoune's community is larger too.

It also uses the "verb->noun" ordering like Vim, but I've gotten used to (and prefer) the "noun->verb" ordering from Kakoune.

I'm going to stick with Kakoune for now, but I'll keep Vis in mind for the future.

**Comment by jgarte** [comment]
> It also uses the "verb->noun" ordering like Vim, but I've gotten used to (and prefer) the "noun->verb" ordering from Kakoune.

I figured this might be weird coming from kakoune. I tried kakoune and noun->verb felt weird to me. 

> As much as I like how it uses Lua, and does parsing instead of regex for syntax highlighting, in other ways it feels less mature than Kakoune. Kakoune's community is larger too.

Yes, I agree. Vis doesn't have a client server architecture or support for lsp, for example.

That said, I like the hackability of vis' clean small code base. I wouldn't want to maintain my own fork of kakoune but maybe that wouldn't be needed...

Nonetheless, I might play with kakoune more in the future once I find the time.

**Comment by evanrelf** [comment]
> I prefer not to preselect the text I will delete as when I get into a flow using text objects I don't have time to look at what I have selected and I find it distracting. I imagine the feature of preselecting can be turned off in kakoune as well as all the dialog windows that pop up.

It's not possible to turn it off in Kakoune because it's a fundamental principle of the editor. It doesn't really take any more keystrokes than Vim, so it doesn't slow you down at all. It just flips the ordering such that you make a selection (and see that selection) before taking action on it.

E.g. Vim has `dap` and Kakoune has `<a-a>pd`, but you can save time by not having to undo if you mess up because you see what you're about to affect.

> `vis-parkour` and `kakoune.el`

I've tried `kakoune.el` and it is not a faithful reproduction of the Kakoune motions. I'd be surprised if `vis-parkour` comes close. It takes a lot of time and effort to write plugins like this and have them feel "right", unfortunately.

> Vis also doesn't have support for lsp yet, for example.

That's actually something I don't care about, funnily enough 😆 I don't like `kak-lsp`.

> That said, I like the hackability of vis' clean small code base. I wouldn't want to maintain my own fork of kakoune...

Vis and Kakoune actually have a pretty similar LOC.

<details>
<summary>Kakoune</summary>

```
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 C++                    56        25795        22805          176         2814
 C++ Header             78        10213         8025          179         2009
 Kakoune script        140        14193        10604         1708         1881
 Makefile                2          207          168            3           36
 Python                  1          228          159            0           69
 RPM Specfile            1          133           93            3           37
 Ruby                    1           80           67            6            7
 Shell                   7          296          243           16           37
 SVG                     1           98           92            3            3
===============================================================================
 Total                 287        51243        42256         2094         6893
===============================================================================
```

</details>

<details>
<summary>Vis</summary>

```
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 C                      32        21862        18482         1534         1846
 C Header               19         3291         1665         1412          214
 Dockerfile              1           34           32            2            0
 Lua                   157        17406        12041         3234         2131
 Makefile                2          244          193            6           45
 Markdown                3          249            0          194           55
 Python                  1          178           47           88           43
 ReStructuredText        7          450          304            0          146
 Shell                   4          949          730           62          157
 Plain Text              1            1            0            1            0
===============================================================================
 Total                 227        44664        33494         6533         4637
===============================================================================
```

</details>

I think C vs C++ and Kakoune script vs Lua is the more important part, not how large the codebases are. I really dislike C and C++, so I probably wouldn't make any meaningful contributions or tweaks to justify a fork anyways. If they used something more modern like Rust or Go, or some higher-level language, I'd consider it.

I do think Lua is far better than Kakoune script, so that's nice.

> Nonetheless, I might play with kakoune more in the future once I find the time. I'm glad you gave vis a try.

I think they're both very cool editors filling a similar niche. I'll keep my eye on Vis for the future 👍 At the moment, I've already spent time getting used to (and liking!) the way Kakoune does things, and Vis feels too Vim-like for my taste. But I can totally see how that would be a benefit for people more comfortable with Vim.

> I'm looking forward to your presentation next Monday!

Thanks!
